#32 Формирование отчета в формате Generic Execution (Sonar)
artbear/1testrunner pull request #33
Opened 2018-05-12 09:58 UTC by arkuznetsov

2018-05-14 15:11 UTC, artbear commented
@arkuznetsov Очень интересно, спасибо!

Пока некогда смотреть :(
работа + подготовка к конференции.

Очень постараюсь посмотреть и выдать обратную связь

2018-05-28 12:18 UTC, artbear requested changes
Отличное дополнение.
Но есть замечания.
@arkuznetsov Исправишь?
затем я приму.

ЗЫ иначе irac на штатном 1testrunner выполнить нельзя :(

2018-05-28 12:18 UTC, artbear commented on testrunner.os
> +		ИЛИ Найти(текстОшибки, "Object method not found ("+имяМетода+")") > 0  Тогда
Откати, плиз, эти строки
```bsl
Если Найти(текстОшибки, "Метод объекта не обнаружен ("+имяМетода+")") > 0 
+		ИЛИ Найти(текстОшибки, "Object method not found ("+имяМетода+")") > 0  Тогда
```
т.к. этот старый вариант неверно работает в 20 релизе :(

2018-05-28 12:18 UTC, artbear commented on testrunner.os
> +	ФорматЛогФайла = "JU";
+ Значение `"JU"` нигде в коде не используется :( 
  + Есть проверка на `GE`
  + Зачем `"JU"` вообще тогда нужно?
+ Предлагаю вместо магических строк (`GE` и `JU`) заюзать фиксированную структуру и обращаться к ее свойствам
  + Например, `ВидыФорматаЛогФайла.JUnit` или `ВидыФорматаЛогФайла.GenericSonar`

2018-05-28 12:18 UTC, artbear commented on testrunner.os
> +	ФорматЛогФайла = "JU";
Примеры есть в 1тестраннере.
Например, `ЗначенияСостоянияТестов`

2018-05-28 12:18 UTC, artbear commented on testrunner.os
> +	ЗаписьXML.Закрыть();
Код дублируется с аналогичным методом в формировании отчета Junit.
Копипаст = зло :)
```bsl
ЗаписьXML = Новый ЗаписьXML;
+	ЗаписьXML.ОткрытьФайл(ПутьОтчетаВФорматеJUnitxml.ПолноеИмя);
+	ЗаписьXML.ЗаписатьБезОбработки(СтрокаХМЛ);
+	ЗаписьXML.Закрыть();
```

2018-05-28 12:18 UTC, artbear commented on testrunner.os
> +	ЗаписьXML.Закрыть();
Предлагаю выделить отдельный метод для этих строк

2018-05-28 12:18 UTC, artbear commented on testrunner.os
> +	Утверждения.ПроверитьНеРавенство(НаборТестов.Количество(), 0);
Предлагаю расшифровать утверждение, чтобы было понятно, в каком месте кода утверждение упало.
Например, 
```bsl
Утверждения.ПроверитьНеРавенство(НаборТестов.Количество(), 0, "Количество тестов равно нуля, что неверно. Метод ЗавершитьЗаписьВФайлОтчетаТестированияВФорматеGExecXML ");
```

2018-05-30 19:52 UTC, arkuznetsov commented on testrunner.os
> +		ИЛИ Найти(текстОшибки, "Object method not found ("+имяМетода+")") > 0  Тогда
Сорри, не понимаю, куда откатить? Я подлил к себе из твоего актуального девелопа там все на месте.

2018-05-30 20:16 UTC, arkuznetsov commented on testrunner.os
> +	ЗаписьXML.Закрыть();
Поправил.

2018-05-30 20:16 UTC, arkuznetsov commented on testrunner.os
> +	Утверждения.ПроверитьНеРавенство(НаборТестов.Количество(), 0);
Поправил.

2018-05-30 20:17 UTC, arkuznetsov commented on testrunner.os
> +	ФорматЛогФайла = "JU";
Добавил структуру с форматами.
В структуре оставил значение JUnit, а также назначение значения по умолчанию для дальнейшего развития.

2018-05-30 20:30 UTC, arkuznetsov commented
@artbear А по что у тебя сборка на трависе поломана?

2018-05-30 20:34 UTC, artbear requested changes

2018-05-30 20:34 UTC, artbear commented on testrunner.os
> +		ИЛИ Найти(текстОшибки, "Object method not found (" + имяМетода + ")") > 0  Тогда
Как я уже писал, откати эти строки, оставь, как у меня сейчас написано.

2018-05-30 20:34 UTC, artbear commented on testrunner.os
> +		ИЛИ Найти(текстОшибки, "Object method not found (" + имяМетода + ")") > 0  Тогда
Иначе на новых релизах движка будут ошибки

2018-05-30 20:36 UTC, arkuznetsov commented on testrunner.os
> +		ИЛИ Найти(текстОшибки, "Object method not found (" + имяМетода + ")") > 0  Тогда
Так вот я  не пойму как у тебя сейчас :-(. Я начинающий волшебник :-)

2018-05-30 20:42 UTC, arkuznetsov commented on testrunner.os
> +		ИЛИ Найти(текстОшибки, "Object method not found (" + имяМетода + ")") > 0  Тогда
Так, вроде въехал.

2018-06-01 14:42 UTC, artbear approved these changes

2018-06-01 14:42 UTC, merged