Добавлена параметризация тестов через аннотации
artbear/1testrunner pull request #44
Opened 2023-05-01 18:40 UTC by EvilBeaver

2023-10-10 19:33 UTC, artbear requested changes

2023-10-10 19:33 UTC, artbear commented on src/Классы/testrunner.os
> +				ВызватьИсключение СтрШаблон("Неверное применение аннотации %1 на методе %2. Ожидаются парамеры-значения, без имен",
опечатка "парамеры"

2023-10-10 19:33 UTC, artbear commented on src/Классы/testrunner.os
> +			ПредставленияПараметров = ПредставленияПараметров + "," + Строка(Параметр.Значение);
ПредставленияПараметров удобно получить сразу после цикла через 

`ПредставленияПараметров  = СтрСоединить(ЗначенияПараметров, ",");`

и тогда не нужно использовать `Сред(ПредставленияПараметров, 2)`

2023-11-06 08:58 UTC, EvilBeaver commented
@artbear полезная функциональность простаивает невлитой

2023-11-08 08:16 UTC, artbear approved these changes

2023-11-08 08:17 UTC, merged