Базовая реализация использования в качестве библиотеки fix #6
artbear/1testrunner pull request #7
Opened 2017-01-21 12:48 UTC by artbear

+ Базовая реализация использования в качестве библиотеки fix #6
+ Выделен отдельный исполняемый файл main.os
+ Исправлены файлы для запуска на различных CI - Jenkins, travis, appveyor
+ Добавлено логирование загрузки тестов

/cc @nixel2007

2017-01-21 12:49 UTC, artbear commented
@nixel2007 Пока реализован совсем базовый вариант.
Аналог командной строки
[Пример](https://github.com/artbear/1testrunner/pull/7/files#diff-d7799408ceb44f6ff23a3b601347b6d9)

2017-01-21 13:17 UTC, nixel2007 requested changes

2017-01-21 13:17 UTC, nixel2007 commented on packagedef
> +		.ИсполняемыйФайл("main.os");
Не надо main.os.  Тогда и имя батника будет main.bat

2017-01-21 13:41 UTC, artbear commented on packagedef
> +		.ИсполняемыйФайл("main.os");
@nixel2007 В ОписаниеПакета из Opm есть метод `ИсполняемыйФайл(Знач Путь, Знач ИмяПриложения = "")`
могу ли я в packagedef пакета указать ИмяПриложения для того, чтобы создавался "правильный" батник с указанным именем ?

2017-01-21 13:52 UTC, nixel2007 commented on packagedef
> +		.ИсполняемыйФайл("main.os");
Да, можно. Код чтения этого свойства прописан вот здесь https://github.com/oscript-library/opm/blob/master/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0%D0%9F%D0%B0%D0%BA%D0%B5%D1%82%D0%B0.os#L356

2017-01-22 09:40 UTC, artbear commented on packagedef
> +		.ИсполняемыйФайл("main.os");
Устанавливаю в
```bsl

Описание.Имя("1testrunner")
		.Версия("1.2")
		.ЗависитОт("logos")
		.ЗависитОт("cmdline")
		.ЗависитОт("tempfiles")
		.ЗависитОт("strings")
		.ВключитьФайл("tests")
		.ВключитьФайл("main.os")
		.ВключитьФайл("testrunner.os")
		.ВключитьФайл("readme.md")
		.ИсполняемыйФайл("main.os", "1testrunner");
```

2017-01-22 12:42 UTC, artbear commented
@nixel2007 В таком варианте (с именем приложения 1testrunner) устраивает?
еще замечания есть? или можно мержить?

2017-01-22 12:55 UTC, nixel2007 commented
@artbear дай мне сутки

2017-01-23 08:52 UTC, nixel2007 commented
Если честно, странноватое апи.
Я должен флаг -runall передать просто внутри массива параметров?
Не юзер-френдли. Может добавить несколько параметров у процедуры ВыполнитьТесты() ?
Путь к каталогу/тесту - это хорошо. а вот тот же -runall - это уже флаг, а не путь (не говоря о том, что -runall должен определяться автоматически в случае каталога)

2017-01-23 10:12 UTC, artbear commented
Пока реализовано совсем базовое АПИ, с минимальной доработкой существующего кода :) - просто передаем такие же параметры, как и в командной строке.
В дальнейшем, конечно, будут выделены специальные методы, соответствующий задачам, выполняемым продуктом

2017-01-23 10:49 UTC, nixel2007 commented
@artbear ты же понимаешь, что смена апи - это немного беда, и надо выпускать новую major-версию с описанием breaking change?
С учетом того, что у нас пока инфраструктура opm не позволяет обрабатывать максимально требуемую версию, это может принести некоторое количество боли.

2017-01-23 10:55 UTC, artbear commented
Хотелось побыстрее тебя сделать счастливее, но не получается.
Буду думать, как реализовать нормальное АПИ.

2017-01-23 10:56 UTC, nixel2007 commented
@artbear Артур 😆 🤣

2017-01-25 20:45 UTC, artbear commented
Реализовал API
+ Метод API ТестироватьФайл
+ Метод API ТестироватьКаталог

/cc @nixel2007

2017-01-25 20:46 UTC, artbear commented
ИМХО текущего API достаточно для тестирования в режиме библиотеки.

2017-01-25 20:55 UTC, nixel2007 commented
Красота!

2017-01-25 21:00 UTC, artbear commented
@nixel2007 Если возражений нет, замержу и выпущу релиз?

2017-01-25 21:07 UTC, nixel2007 commented
Да, давай

2017-01-25 21:46 UTC, merged